# .github/workflows/deploy.yml
name: Deploy to ECS

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository code
      - name: Check out the repo
        uses: actions/checkout@v3

      # 2. Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS \
              --password-stdin 851725289587.dkr.ecr.us-east-1.amazonaws.com

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build --platform=linux/amd64 \
            -t hellonb:latest .

      # 5. Tag and push image to ECR
      - name: Push Docker image to ECR
        run: |
          docker tag hellonb:latest \
            851725289587.dkr.ecr.us-east-1.amazonaws.com/hellonb-repo:latest
          docker push \
            851725289587.dkr.ecr.us-east-1.amazonaws.com/hellonb-repo:latest

      # 6. Update ECS service to pull new image
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster hellonb-cluster \
            --service hellonb-service \
            --force-new-deployment
